### ISSUE TITLE
Initial project setup

### ISSUE THREAD

**Issue by jirutka** [asciidoctor/asciidoc-grammar-prototype#2]
@mojavelinux I’ve created basic project setup with Gradle, ANTLR4 and Spock, you can take it from https://github.com/jirutka/asciidoc-grammar-prototype.

It’s not possible to fork an empty repository and I don’t know if it’s even possible to send pull request without forking the repository. Thus I’m writing an issue instead of just sending PR.

Note: I haven’t set publication to Maven repository yet, I need to learn how to do it properly in Gradle and it’s not necessary for now anyway.

**Comment by mojavelinux** [comment]
Thanks for kicking this off, @jirutka! I'll clone your fork, connect it to this repository and push. I should have realized it wasn't possible to clone an empty repo.

**Comment by mojavelinux** [comment]
Merged! Experiment underway!
